server:
  port: 18080
  servlet:
    context-path: /psw

logging:
  level:
    com.papaswatch: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        hbm2ddl:
          auto: none
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 200
        jdbc:
          fetch_size: 100
  datasource:
    hikari:
      maximum-pool-size: 10
    jdbc-url: jdbc:postgresql://localhost:5432/papaswatch
    driver-class-name: org.postgresql.Driver
    username: twave
    password: eva77

user.session.expired: 1800

images:
  product:
    dir: ${PRODUCT_DIR:./src/main/resources/products}

apis:
  # 국세청
  tax:
    # 사업자등록정보 조회
    business:
      key: 6rQW42fvuau%2F%2BpjtYVf5X9LXgY1oTZaRJ7YLLoiEXbGslJiQC0pQroHH0Pd%2F2tAlY3Nu%2F13mGD60NEnPGw0ywg%3D%3D